// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK0nn070RQAkmL_EzzfKo8HyBw78wyWzg',
    appId: '1:875606607101:web:baa1cf0e22b0d52c466a94',
    messagingSenderId: '875606607101',
    projectId: 'gaurikeerthana-residency-c3ba4',
    authDomain: 'gaurikeerthana-residency-c3ba4.firebaseapp.com',
    storageBucket: 'gaurikeerthana-residency-c3ba4.firebasestorage.app',
    measurementId: 'G-X365HD4ESW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAPWgbhQXY6tVa1Txraf5QR30KT_miNYI',
    appId: '1:875606607101:android:de7d2b26d2599502466a94',
    messagingSenderId: '875606607101',
    projectId: 'gaurikeerthana-residency-c3ba4',
    storageBucket: 'gaurikeerthana-residency-c3ba4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAPWgbhQXY6tVa1Txraf5QR30KT_miNYI',
    appId: '1:875606607101:ios:de7d2b26d2599502466a94', // Guessed appId based on android pattern
    messagingSenderId: '875606607101',
    projectId: 'gaurikeerthana-residency-c3ba4',
    storageBucket: 'gaurikeerthana-residency-c3ba4.firebasestorage.app',
    iosBundleId: 'com.example.gaurikeerthana_residency',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAPWgbhQXY6tVa1Txraf5QR30KT_miNYI',
    appId: '1:875606607101:ios:de7d2b26d2599502466a94',
    messagingSenderId: '875606607101',
    projectId: 'gaurikeerthana-residency-c3ba4',
    storageBucket: 'gaurikeerthana-residency-c3ba4.firebasestorage.app',
    iosBundleId: 'com.example.gaurikeerthana_residency',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK0nn070RQAkmL_EzzfKo8HyBw78wyWzg',
    appId: '1:875606607101:web:baa1cf0e22b0d52c466a94',
    messagingSenderId: '875606607101',
    projectId: 'gaurikeerthana-residency-c3ba4',
    authDomain: 'gaurikeerthana-residency-c3ba4.firebaseapp.com',
    storageBucket: 'gaurikeerthana-residency-c3ba4.firebasestorage.app',
    measurementId: 'G-X365HD4ESW',
  );
}
